name: Build Image

on:
  workflow_dispatch:
    inputs:
      updateConfigRepo:
        type: choice
        default: false
        required: true
        options:
          - true
          - false
  push:
    branches: [ main ]

env:
  IMAGE_REPO: ghcr.io/
  IMAGE_NAME: flutter-global/exchange-quarkus/eqs
  VERSION: 1.0-${{github.run_number}}
  DOCKER_REPOSITORY: docker.pkg.github.com/flutter-global/exchange-quarkus/eqs

jobs:
  build-image:
    runs-on: centos-self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Set up Java
        uses: Flutter-Tech/ppb-java@v1.0.0
        with:
          java-version: '17'

      - name: Docker login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u Flutter-Global --password-stdin

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.8.2

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run tests
        id: test_job
        run: mvn verify

      - name: Update version
        id: update_version
        run: |
          echo "PROJECT_VERSION=${{ env.VERSION }}" >> $GITHUB_ENV
          mvn -B versions:set -DnewVersion=${{ env.PROJECT_VERSION }}

      - name: Build native executable
        id: build_native_executable
        run: ./mvnw package -Dnative -Dquarkus.native.container-build=true

      - name: Build and Push Docker Image
        id: build_and_push_docker_image
        run: |
          docker build -f src/main/docker/Dockerfile.native -t ghcr.io/${{ env.IMAGE_REPO }}/my-app:${{ env.PROJECT_VERSION }} .
          docker push ghcr.io/${{ github.repository }}/my-app:${{ env.PROJECT_VERSION }}