name: Build Image

on:
  workflow_dispatch:
    inputs:
      updateConfigRepo:
        type: choice
        default: false
        required: true
        options:
          - true
          - false
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  VERSION: 1.0-${{github.run_number}}

jobs:
  build-image:
    runs-on: ubuntu-latest

#    Sets the permissions granted to the GITHUB_TOKEN for the actions in this job.
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.8.2

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

#      - name: Run tests
#        id: test_job
#        run: mvn verify

      - name: Set PROJECT_VERSION
        run: echo "PROJECT_VERSION=${{ env.VERSION }}" >> $GITHUB_ENV

      - name: Update version
        id: update_version
        run: |
          echo "Project Version is ${{ env.PROJECT_VERSION }}"
          mvn -B versions:set -DnewVersion=${{ env.PROJECT_VERSION }}

      - name: Build native executable
        id: build_native_executable
#        run: ./mvnw package -Dnative -Dquarkus.native.container-build=true
        run: ./mvnw package -DskipTests

      - name: test github_token
        id: test_github_token
        run: |
          echo "registry: ${{ env.REGISTRY }}"
          echo "username: ${{ github.actor }}"
          echo "password: ${{ secrets.GITHUB_TOKEN }}"

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Docker test
        id: docker_test
        run: |
          echo "tags: ${{ steps.meta.outputs.tags }} "
          echo "labels: ${{ steps.meta.outputs.labels }} "
          echo "image_name: ${{ env.IMAGE_NAME }} "
          echo "version tag: ${{ env.PROJECT_VERSION }} "

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.PROJECT_VERSION }}
          labels: ${{ steps.meta.outputs.labels }}
#          file: src/main/docker/Dockerfile.native
          file: src/main/docker/Dockerfile.jvm

      - name: Docker test
        id: docker_test_2
        run: |
          docker images